HOST = '127.0.0.1'
LIVE_ACCT_PORT = 7496
PAPER_ACCT_PORT = 7497

HISTORICAL_DATA_ID = 1
ANALYSIS_ID = 2
NAV_ID = 3

IB_DATE_FMT = '%Y%m%d %H:%M:%S'
PATH = r'G:\My Drive\trading\data'
HISTORICAL_TRADES_DB = 'Historical TRADES.db'
HISTORICAL_ADJ_LAST_DB = 'Historical ADJUSTED_LAST.db'

BID_SIZE_TICK_TYPE = 0
BID_PRICE_TICK_TYPE = 1
ASK_PRICE_TICK_TYPE = 2
ASK_SIZE_TICK_TYPE = 3
LAST_PRICE_TICK_TYPE = 4
LAST_SIZE_TICK_TYPE = 5
CLOSE_PRICE_TICK_TYPE = 9
LAST_RTH_TRADED_PRICE = 57
DELAYED_LAST_PRICE_TICK_TYPE = 68
DELAYED_CLOSE_PRICE_TICK_TYPE = 75

LIVE_MKT_DATA_TYPE = 1
FROZEN_MKT_DATA_TYPE = 2
DELAYED_MKT_DATA_TYPE = 3
DELAYED_FROZEN_MKT_DATA_TYPE = 4

CURRENCIES_PRIOR_TO_USD = ['EUR', 'GBP', 'CHF', 'AUD']
CURRENCIES_AFTER_USD = ['JPY', 'SGD', 'HKD', 'CAD', 'NOK', 'DKK', 'SEK']

BENCHMARK = 'SPY'
SPDR_SECTOR_UNIVERSE = ['XLK', 'XLF', 'XLP', 'XLU', 'XLY', 'XLB', 'XLE', 'XLI', 'XLV']


def determineDatabaseToUse(whatToShow):
    if whatToShow == 'TRADES':
        return HISTORICAL_TRADES_DB
    elif whatToShow == 'ADJUSTED_LAST':
        return HISTORICAL_ADJ_LAST_DB
    else:
        raise NotImplementedError('There seems to be no variable representing the database for %s' % whatToShow)
